name: TKDconda
channels:
  - defaults
dependencies:
  - ca-certificates=2025.2.25
  - openssl=1.1.1w
  - pip=25.1
  - python=3.9.0
  - setuptools=78.1.1
  - sqlite=3.45.3
  - vc=14.42
  - vs2015_runtime=14.42.34433
  - wheel=0.45.1
  - pip:
      - certifi==2025.7.9
      - charset-normalizer==3.4.2
      - click==8.1.8
      - colorama==0.4.6
      - contourpy==1.3.0
      - cycler==0.12.1
      - fonttools==4.58.5
      - idna==3.10
      - importlib-resources==6.5.2
      - joblib==1.5.1
      - kiwisolver==1.4.7
      - matplotlib==3.9.4
      - numpy==2.0.2
      - packaging==25.0
      - pandas==2.3.1
      - pillow==11.3.0
      - pyparsing==3.2.3
      - pyqt6==6.4.2
      - pyqt6-plugins==6.4.2.2.3
      - pyqt6-qt6==6.4.3
      - pyqt6-sip==13.10.2
      - pyqt6-tools==6.4.2.3.3
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.1.1
      - pytz==2025.2
      - qt6-applications==6.4.3.2.3
      - qt6-tools==6.4.3.1.3
      - requests==2.32.4
      - scikit-learn==1.6.1
      - scipy==1.13.1
      - seaborn==0.13.2
      - six==1.17.0
      - threadpoolctl==3.6.0
      - tzdata==2025.2
      - urllib3==2.5.0
      - zipp==3.23.0
prefix: C:\Users\giuli\anaconda3\envs\TKDconda
